C/project_advance_views/blog/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.home, name = 'home'),
    path('blog/', views.blog, name = 'blog'),
    path('author/', views.author, name = 'author'),
    path('mentor/', views.mentor, name = 'mentor'),
    path('mentee/', views.mentee, name = 'mentee'),
    path('form/', views.form, name = 'form'),
    path('form/update', views.formupdate, name = 'formupdate'),
    path('blog/<int:blog_id>', views.detail, name='baca_selengkapnya'),
]

C/project_advance_views/project_advance_views/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

C/project_advance_views/blog/models.py
from django.db import models
from datetime import datetime

# Create your models here.

class Blog(models.Model):
    Gambar            = models.CharField(max_length = 200)
    Tanggal           = models.DateTimeField(auto_now=True)
    Comment           = models.CharField(max_length = 200)
    Title             = models.CharField(max_length = 200)
    Content           = models.TextField(max_length = 2000)

class Mentor(models.Model):
    Gambar          = models.CharField(max_length = 200)
    Nama            = models.CharField(max_length = 200)
    Experience      = models.CharField(max_length = 200)
    Quote           = models.TextField(max_length = 200)

class Mentee(models.Model):
    Gambar          = models.CharField(max_length = 200)
    Name            = models.CharField(max_length = 200)
    Quote           = models.TextField(max_length = 200)

C/project_advance_views/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Blog, Mentor, Mentee

# Create your views here.

def home(request):
    return render(request, 'home.html',{})

def blog(request):
    blogs = Blog.objects.all()
    return render(request, 'blog.html',{'blogs':blogs})

def mentee(request):
    mentees = Mentee.objects.all()
    return render(request, 'mentee.html',{'mentees':mentees})

def mentor(request):
    mentors = Mentor.objects.all()
    return render(request, 'mentor.html',{'mentors':mentors})

def author(request):
    return render(request, 'author.html',{})

def form(request):
    return render(request, 'form.html',{})

def formupdate(request):
    judul   = request.POST['judul_post']
    konten  = request.POST['content_post']
    link    = request.POST['link_gambar']
    new = Blog(Title = judul, Content = konten, Gambar = link)
    new.save()
    # blogs = Blog.objects.all()
    return redirect('/blog')
    
def detail(request, blog_id):
    blogs = get_object_or_404(Blog,pk = blog_id)
    return render(request, 'baca_selengkapnya.html',{'blogs': blogs})

C/project_advance_views/blog/templates/author.html
{% extends 'base.html' %}

{% block Title %}AUTHOR{% endblock %}
{% block tambahan %}Blog{% endblock %}


{% block content %}
{% load static %}


<div class="wrap-home--content">
    <div class="foto_author">
        <img src="{% static 'img/author/author.jpg'%}">
    </div>
    <div class="nama_author">
        <h3>Nama Author</h3>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-2"></div>
            <div class="col-8 summary">
                <p>
                    <strong>Please Write your Summary,</strong> lorem Ipsum Dolor Sit Amet. Lorem Ipsum Sit Amet. Lorem Ipsum Sit Amet. Lorem Ipsum Sit Amet. Lorem Ipsum Sit Amet. Lorem Ipsum Sit Amet. Lorem Ipsum Sit Amet.
                </p>
            </div>
            <div class="col-2"></div>
        </div>
    </div>
    <div class="container detail_profile">
        <div class="row">
            <div class="col-2"></div>
            <div class="col-2 ">Alamat</div>
            <div class="col-6 ">: Alamat Author</div>
            <div class="col-2"></div>
        </div>
    </div>
    <div class="container detail_profile">
        <div class="row">
            <div class="col-2"></div>
            <div class="col-2 ">Telephone</div>
            <div class="col-6 ">: Author's Telephone</div>
            <div class="col-2"></div>
        </div>
    </div>
    <div class="container detail_profile">
        <div class="row">
            <div class="col-2"></div>
            <div class="col-2 ">Education</div>
            <div class="col-6 ">: Author's Education</div>
            <div class="col-2"></div>
        </div>
    </div>
    <div class="container detail_profile">
        <div class="row">
            <div class="col-2"></div>
            <div class="col-2 ">Profression</div>
            <div class="col-6 ">: Author's Profression</div>
            <div class="col-2"></div>
        </div>
    </div>
    <div class="container detail_profile">
        <div class="row">
            <div class="col-2"></div>
            <div class="col-2 ">Nationality</div>
            <div class="col-6 ">: Author's Nationality</div>
            <div class="col-2"></div>
        </div>
    </div>
    <div class="container detail_profile">
        <div class="row">
            <div class="col-2"></div>
            <div class="col-2 ">Company</div>
            <div class="col-6 ">: Author's Company</div>
            <div class="col-2"></div>
        </div>
    </div>
    <div class="container detail_profile">
        <div class="row">
            <div class="col-2"></div>
            <div class="col-2 ">Email</div>
            <div class="col-6 ">: Author's Email</div>
            <div class="col-2"></div>
        </div>
    </div>
    <div class="container detail_profile">
        <div class="row">
            <div class="col-2"></div>
            <div class="col-2 ">Address</div>
            <div class="col-6 ">: Author's Address</div>
            <div class="col-2"></div>
        </div>
    </div>
    <div class="maps">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3951.314233480313!2d112.60827644979209!3d-7.966441481577961!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e7882865ded0697%3A0xa77fa961a7c4e4b7!2sSepulsa%20Lodge%20Malang!5e0!3m2!1sen!2sid!4v1575981224448!5m2!1sen!2sid" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
    </div>
</div>
{% endblock %}

C/project_advance_views/blog/templates/baca_selengkapnya.html
{% extends 'base.html' %}

{% block Title %}DETAILS{% endblock %}
{% block tambahan %}Blog{% endblock %}

{% block content %}
{% load static %}


<div class="container">
    <div class="row">
        <div class="col-2"></div>
        <div class="isiblog">
            <div class="col-8">
                <div class="fotokendala">
                    <img src="{{blogs.Gambar}}">
                </div>
                <div class="container ketfoto">
                    <div class="row">
                        <div class="col-6 tanggal">
                            <p>{{blogs.Tanggal}}</p>
                        </div>
                        <div class="col-6 comment">
                            <p>{{blogs.Comment}}</p>
                        </div>
                    </div>
                </div>
                <h1>{{blogs.Title}}</h1>
                <p>{{blogs.Content}}</p>
            </div>
        </div>
        <div class="col-2"></div>
    </div>
</div>
{% endblock %}

C/project_advance_views/blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width", initial-scale="1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'js/bootstrap.min.js'%}">
    <link rel="stylesheet" href="{% static 'css/main.css'%}">
    <title>{% block Title %}{% endblock %}</title>
</head>
<body>
    <header>
        <div class="container">
            <div class="row align-items-center">
                <div class="col-md-7 col-sm-12 altalogo">
                    <a href="{% url 'blog:home' %}">Alpha Tech Academy</a>
                </div>
                <div class="col-md-5 option1">
                    <div class="header-nav1">
                        <ul class="header-nav__list1 list-unstyled">
                            <li>
                                <a href="{% url 'blog:home' %}">Home</a>
                            </li>
                            <li>
                                <a href="{% url 'blog:blog' %}">Blog</a>
                            </li>
                            <li>
                                <a href="{% url 'blog:mentor' %}">Mentor</a>
                            </li>
                            <li>
                                <a href="{% url 'blog:mentee' %}">Mentee</a>
                            </li>
                            <li>
                                <a href="{% url 'blog:author' %}">Author</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <div class="container-fluid atas">
        <div class="container">
            <div class="row">
                <div class="col-12"><p><br><br><br><br></p></div>
                <div class="col-12">
                    <div class="logo_ta">
                        <img src="{% static 'img/title/alpha-logo.png'%}">
                    </div>
                </div>
                <div class="col-3"></div>
                <div class="col-6">
                    <div class="home1">
                        <h1>Alpha Tech Academy {% block tambahan %}{% endblock %}</h1>
                        <p>Alpha Tech Academy is a tech talent incubator that gives everyone (even non IT background) a chance to be a professional Tech Talent within 3 month. Contact Person: Email:academy@alphatech.id Mobile phone:</p>
                        <p>0877 9609 9530</p>
                    </div>
                </div>
                <div class="col-3"></div>
            </div>
        </div>
    </div>
    <div class="warp-base--content">
        {% block content %}
        {% endblock %}
    </div>
    <footer>
        <div class="container-fluid foot1">
        <div class="col-4 line1">
            <h3>Our Product: </h3>
            <img src="{% static 'img/footer/logo-grey-alphapay.png'%}">
            <img src="{% static 'img/footer/logo-grey-sepulsa.png'%}">
            <img src="{% static 'img/footer/logo-grey-alphabill.png'%}">
        </div>
        </div>
        <div class="container-fluid foot2">
            <div class="row line2">
                <div class="col3 contact">
                    <h3>Contact Person: </h3>
                </div>
                <div class="col3 mobile">
                    <p>Mobile phone: 0877 9609 9530.  Email:</p>
                </div>
                <div class="col3 email">
                    <p>academy@alterra.id</p>
                </div>
            </div>
        </div>
</footer>
</body>
</html>

C/project_advance_views/blog/templates/blog.html
{% extends 'base.html' %}

{% block Title %}BLOG{% endblock %}
{% block tambahan %}Blog{% endblock %}

{% block content %}
{% load static %}

<div class="wrap-home--content">
    <div class="container">
        <div class="row">
            <div class="col-2"></div>
            {% for blog in blogs%}
            <div class="isiblog">
                <div class="col-8">
                    <div class="fotokendala">
                        <img src="{{blog.Gambar}}">
                    </div>
                    <div class="container ketfoto">
                        <div class="row">
                            <div class="col-6 tanggal">
                                <p>{{blog.Tanggal}}</p>
                            </div>
                            <div class="col-6 comment">
                                <p>{{blog.Comment}}</p>
                            </div>
                        </div>
                    </div>
                    <h1>{{blog.Title}}</h1>
                    <p>{{blog.Content|safe|truncatewords:"20"|linebreaks}}</p>
                    <div class="baca_selengkapnya">
                        <a href="{% url 'blog:baca_selengkapnya' blog.id %}">Baca Selengkapnya</a>
                    </div>
                </div>
            </div>
            {% endfor %}
            <div class="col-3"></div>
            <div class='link_form'>
                <p>Apakah anda ingin menginput Artikel baru?</p>
                <a href="{% url 'blog:form' %}">Submit here</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

C/project_advance_views/blog/templates/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width", initial-scale="1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'js/bootstrap.min.js'%}">
    <link rel="stylesheet" href="{% static 'css/main.css'%}">
    <title>FORM</title>
</head>
<body>
    <header>
        <div class="container">
            <div class="row align-items-center">
                <div class="col-md-7 col-sm-12 altalogo">
                    <a href="{% url 'blog:home' %}">Alpha Tech Academy</a>
                </div>
                <div class="col-md-5 option1">
                    <div class="header-nav1">
                        <ul class="header-nav__list1 list-unstyled">
                            <li>
                                <a href="{% url 'blog:home' %}">Home</a>
                            </li>
                            <li>
                                <a href="{% url 'blog:blog' %}">Blog</a>
                            </li>
                            <li>
                                <a href="{% url 'blog:mentor' %}">Mentor</a>
                            </li>
                            <li>
                                <a href="{% url 'blog:mentee' %}">Mentee</a>
                            </li>
                            <li>
                                <a href="{% url 'blog:author' %}">Author</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <div class="form_body">
        <form method='POST' action="{% url 'blog:formupdate' %}">
            {% csrf_token %}
            <label id='judul_artikel'>Judul Artikel : </label>
            <br>
            <input type="text" name='judul_post' id='judul_post'></input>
            <br><br>
            <label id='content_artikel'>Konten Artikel : </label>
            <br>
            <textarea name='content_post' cols="30" rows="10" id='content_post'></textarea>
            <br><br>
            <label id='link_gambar'>Link Gambar Artikel : </label>
            <input type="text" name='link_gambar' id='link_gambar'></input>
            <br><br>
            <input type="submit" value="submit"></input>
        </form>
    </div>
    <footer>
        <div class="container-fluid foot1">
        <div class="col-4 line1">
            <h3>Our Product: </h3>
            <img src="{% static 'img/footer/logo-grey-alphapay.png'%}">
            <img src="{% static 'img/footer/logo-grey-sepulsa.png'%}">
            <img src="{% static 'img/footer/logo-grey-alphabill.png'%}">
        </div>
        </div>
        <div class="container-fluid foot2">
            <div class="row line2">
                <div class="col3 contact">
                    <h3>Contact Person: </h3>
                </div>
                <div class="col3 mobile">
                    <p>Mobile phone: 0877 9609 9530.  Email:</p>
                </div>
                <div class="col3 email">
                    <p>academy@alterra.id</p>
                </div>
            </div>
        </div>
</footer>
</body>
</html>

C/project_advance_views/blog/templates/home.html
{% extends 'base.html' %}

{% block Title %}HOME{% endblock %}
{% block tambahan %}{% endblock %}

{% block content %}
{% load static %}

<div class="wrap-home--content">
    <!-- ==================================== 3 Gambar ============================================ -->
    <div class="container con3">
        <div class="row">
            <div class="col-5 gambarhome3">
                <div class='gambarhome3a'>
                    <img src="{% static 'img/home/benefit.png'%}">
                </div>
                <div class='gambarhome3b'>
                    <img src="{% static 'img/home/search-job.png'%}">
                </div>
                <div class='gambarhome3c'>
                    <img src="{% static 'img/home/get-paid.png'%}">
                </div>
            </div>
            <div class="col-7 bagian3">
                <div class='tech'>
                    <h2>Learn awesome tech</h2>
                    <p>You will learn about programming language, such as Python and Javascript, build back-end apps using Flask framework woth microservice concept, built client-site apps using React Library, etc.</p>
                </div>
                <div class='job'>
                    <h2>Land new job</h2>
                    <p>If you can pass this awesome program, you will be part of our reliable tech team for especially Software Engineer and other tech position such as Quality Engineer, System Analyst, etc.</p>
                </div>
                <div class='paid'>
                    <h2>Get paid to learn</h2>
                    <p>Join for free and earn some money. Yes you read that right, no registration fee required to enter this program. To make things even better, you will receive pocket money just for participatin. Cool, right?</p>
                </div>
            </div>
        </div>
    </div>
    <!-- =================================== Who we are =============================================== -->
    <div class="container who">
        <div class="row">
            <div class="col-5 gambarhome4">
                <img src="{% static 'img/home/mission.png'%}">
            </div>
            <div class="col-7 bagian4">
                <div class='who'>
                    <h2>Who are we?</h2>
                    <p>Alpha Tech Academy is a tech talent incubation that gives anyone any chance (not even an IT background) to learn within 3 month of being a professional Tech Talent. What is our mission? We want to improve capability Tech Talent in Indonesia</p>
                    <br><br>
                </div>
                <div class='what'>
                    <h2>What is our mission?</h2>
                    <p>We want to improve capability Tech Talent in Indonesia</p>
                </div>   
            </div>
        </div>
    </div>
    <div class="will_you_learn"><h2> What will you learn? </h2></div>
    <!-- ================================== list program ============================================= -->
    <div class="container listprog1">
        <div class="row">
            <div class="col-3 learn1">
                <div class="html">
                    <img src="{% static 'img/home/learn-html.png'%}">
                </div>
            </div>
            <div class="col-3 learn2">
                <div class="python">
                    <img src="{% static 'img/home/learn-programming.png'%}">
                </div>
            </div>
            <div class="col-3 learn3">
                <div class="git">
                    <img src="{% static 'img/home/learn-git.png'%}">
                </div>
            </div>
            <div class="col-3 learn4">
                <div class="restapi">
                    <img src="{% static 'img/home/learn-api.png'%}">
                </div>
            </div>
        </div>
    </div>
    <!-- ================================= next baris ===================================== -->
    <div class="container listprog1">
        <div class="row">
            <div class="col-3 learn1">
                <div class="html">
                    <img src="{% static 'img/home/learn-react.png'%}">
                </div>
            </div>
            <div class="col-3 learn2">
                <div class="python">
                    <img src="{% static 'img/home/learn-tdd.png'%}">
                </div>
            </div>
            <div class="col-3 learn3">
                <div class="git">
                    <img src="{% static 'img/home/learn-server.png'%}">
                </div>
            </div>
            <div class="col-3 learn4">
                <div class="scrum">
                    <img src="{% static 'img/home/learn-scrum.png'%}">
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

C/project_advance_views/blog/templates/mentee.html
{% extends 'base.html' %}

{% block Title %}MENTEE{% endblock %}
{% block tambahan %}{% endblock %}

{% block content %}
{% load static %}

<div class="wrap-home--content">
    <div class="our_mentee">
        <h3>Our Mentee</h3>
    </div>
    {% for mentee in mentees%}
    <div class="container isi_mentee">
        <div class="row">
            <div class="col-4 steve">
                <img src="{% static ''%}{{mentee.Gambar}}">
            </div>
            <div class="col-8 steve_word">
                <h4>{{mentee.Name}}</h4>
                <p>{{mentee.Quote}}</p>
            </div>
        </div>
    </div>
    {% endfor %}
    
</div>
{% endblock %}

C/project_advance_views/blog/templates/mentor.html
{% extends 'base.html' %}

{% block Title %}MENTOR{% endblock %}
{% block tambahan %}{% endblock %}

{% block content %}
{% load static %}

<div class="wrap-home--content">
    <div class="our_mentee">
        <h3>Our Mentor</h3>
    </div>
    {% for mentor in mentors%}
    <div class="container isi_mentee">
        <div class="row">
            <div class="col-4 andreas">
                <img src="{% static ''%}{{mentor.Gambar}}">
            </div>
            <div class="col-8 andreas_word">
                <h4>{{mentor.Nama}}</h4>
                <h5>{{mentor.Experience}}</h5>
                <h6>{{mentor.Quote}}</h6>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}